const numero1=(Number(prompt("escolha numero desejado ?")))
if(confirm(" deseja multiplicar numero1 por mais algum numero especifico ? ")){
     const numero2=Number(prompt("digite numero2 "))
     console.log(numero1*numero2)
 }  else {
     console.log(numero1)
    
 }
 
 const um=numero1*1
 const dois=numero1*2
 const tres =numero1*3
 const quatro=numero1*4
 const cinco=numero1*5
 const seis=numero1*6
 const sete =numero1*7
 const oito =numero1*8
 const nove =numero1*9
 const dez =numero1*10
 console.log(` por um :${um} 
 por dois :${dois}
 por tres : ${tres} 
 por quatro :${quatro}
 por cinco : ${cinco}
 por seis : ${seis}
 por sete : ${sete} 
 por oito :${oito} 
 por nove : ${nove} 
 por dez : ${dez} `)     
 
     
 